### ISSUE TITLE
Review: Signin.jsx and AddMedication.jsx

### ISSUE THREAD

**Issue by alyssandra-cabading** [minerva-medical/minerva-matrp#100]
## Review Branch

* [review-100](https://github.com/minerva-medical/minerva-matrp/issues/100)

## Files to be Reviewed

* [Signin.jsx](https://github.com/minerva-medical/minerva-matrp/blob/main/app/imports/ui/pages/Signin.jsx)  
* [AddMedication.jsx](https://github.com/minerva-medical/minerva-matrp/blob/main/app/imports/ui/components/AddMedication.jsx)

## Checklists

* [Architecture](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-architecture-checklist)
* [Design](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-design-checklist)
* [JS](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-js-checklist)
* [React](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-react-checklist)
* [UI](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-ui-checklist)

## Specific Requests for this review 

Reviewing the Sign-In page to evaluate changes in accordance to customer request.
Reviewing the Add Medication page as there should be additional changes to dropdown components.

## Due Date 

12:00 pm Tuesday, November 16 2021
## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by alyssandra-cabading** [comment]
### REVIEW 5
[Signin.jsx
](https://github.com/minerva-medical/minerva-matrp/blob/main/app/imports/ui/pages/Signin.jsx)

_Architecture_
> Looks Good

_Design_
> Keep it consistent with comment references, for example, the usage of “sign in” and “login”. Other than that, it looks good.

_Javascript and ESLint Checklist_
> Looks Good

_React_
> Looks Good

_UI_
> Looks Good. Maybe change the color of the “REGISTER” link at the bottom. It clashes with the color of the background, perhaps making it a slightly darker shade of blue.
----------------------------------------------------------------------------------------------------------------------------
[AddMedication.jsx
](https://github.com/minerva-medical/minerva-matrp/blob/main/app/imports/ui/components/AddMedication.jsx)

_Architecture_
> Looks Good

_Design_
> Comments have significantly improved. They’re not too long, and they are clear enough to understand the functions of each segment. There are unused codes commented out, and by the looks of it that is for future implementation.

_Javascript and ESLint Checklist_
> Looks Good

_React_
> Looks Good

_UI_
> Looks Good

**Comment by mujtaba-a-quadri** [comment]
Signin.jsx:

Architecture
AR-01: file name is not in camelCase

Design
Fulfills all design requirements

Javascript/ESLint
Fulfills all JS/ESLint requirements 

React
Fulfills all react requirements

UI
Fulfills all UI requirements.


AddMedication.jsx:

Architecture
AR-01: file name is not in camelCase

Design
DE-05: L33 unneeded commented out line

Javascript/ESLint
Fulfills all JS/ESLint requirements 

React
RE-06: L223, define a const to compute the properties then return with object shorthand notation (currently properties are computer in return)

UI
UI-02: layout is not optimized for mobile devices (form itself is fine but the navbar and buttons at the top look a little off)
UI-03: the dropdowns do not make the mouse give the clicker icon (they give a cursor for typing instead)

**Comment by glarita** [comment]
## Signin.jsx

### Architecture 

- requirements met

### Design

- requirements met

### JavaScript

-requirements met

### React

- requirements met

###  UI

- not compatible for mobile yet


## AddMedication.jsx

### Architecture 

- requirements met

### Design

- requirements met

### JavaScript

- console.log statement on line 185 

### React

- requirements met

###  UI

- not compatible for mobile yet

**Comment by alyssandra-cabading** [comment]
### REVIEW 5
[Signin.jsx
](https://github.com/minerva-medical/minerva-matrp/blob/main/app/imports/ui/pages/Signin.jsx)

_Architecture_
> Looks Good

_Design_
> Keep it consistent with comment references, for example, the usage of “sign in” and “login”. Other than that, it looks good.

_Javascript and ESLint Checklist_
> Looks Good

_React_
> Looks Good

_UI_
> Looks Good. Maybe change the color of the “REGISTER” link at the bottom. It clashes with the color of the background, perhaps making it a slightly darker shade of blue.
----------------------------------------------------------------------------------------------------------------------------
[AddMedication.jsx
](https://github.com/minerva-medical/minerva-matrp/blob/main/app/imports/ui/components/AddMedication.jsx)

_Architecture_
> Looks Good

_Design_
> Comments have significantly improved. They’re not too long, and they are clear enough to understand the functions of each segment. There are unused codes commented out, and by the looks of it that is for future implementation.

_Javascript and ESLint Checklist_
> Looks Good

_React_
> Looks Good

_UI_
> Looks Good
