### ISSUE TITLE
Review: DispenseLog.jsx and AddMedication.jsx

### ISSUE THREAD

**Issue by glarita** [minerva-medical/minerva-matrp#45]
## Review Branch

* [review-45](https://github.com/minerva-medical/minerva-matrp/issues/45)

## Files to be Reviewed

* [DispenseLog.jsx](https://github.com/minerva-medical/minerva-matrp/blob/main/app/imports/ui/pages/DispenseLog.jsx)  
* [AddMedication.jsx](https://github.com/minerva-medical/minerva-matrp/blob/main/app/imports/ui/components/AddMedication.jsx)

## Checklists

* [Architecture](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-architecture-checklist)
* [Design](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-design-checklist)
* [JS](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-js-checklist)
* [React](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-react-checklist)
* [UI](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-ui-checklist)

## Specific Requests for this request 

Reviewing Dispense page as there should now be active functionality for the collections

Does the code for the Add Medication page make sense to you? Is there another way that you can think of making this code cleaner if possible?

## Due Date 

12:00 pm Thursday, October 14 2021
## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by cammoore** [comment]
## DispenseLog.jsx

Remove commented line.
https://github.com/minerva-medical/minerva-matrp/blob/0bbbc9d57c8d246ff79633c27158f9ccb933f210/app/imports/ui/pages/DispenseLog.jsx#L5

Use object deconstruction.
https://github.com/minerva-medical/minerva-matrp/blob/0bbbc9d57c8d246ff79633c27158f9ccb933f210/app/imports/ui/pages/DispenseLog.jsx#L41

Why use a div?
https://github.com/minerva-medical/minerva-matrp/blob/0bbbc9d57c8d246ff79633c27158f9ccb933f210/app/imports/ui/pages/DispenseLog.jsx#L44

Comment refers to Stuff
https://github.com/minerva-medical/minerva-matrp/blob/0bbbc9d57c8d246ff79633c27158f9ccb933f210/app/imports/ui/pages/DispenseLog.jsx#L150

drugTypes props isn't used.
https://github.com/minerva-medical/minerva-matrp/blob/0bbbc9d57c8d246ff79633c27158f9ccb933f210/app/imports/ui/pages/DispenseLog.jsx#L139

## AddMedication.jsx

action values should be in an exported object.
https://github.com/minerva-medical/minerva-matrp/blob/0bbbc9d57c8d246ff79633c27158f9ccb933f210/app/imports/ui/components/AddMedication.jsx#L24

Use object deconstruction.
https://github.com/minerva-medical/minerva-matrp/blob/0bbbc9d57c8d246ff79633c27158f9ccb933f210/app/imports/ui/components/AddMedication.jsx#L82

Use Uniforms?
https://github.com/minerva-medical/minerva-matrp/blob/0bbbc9d57c8d246ff79633c27158f9ccb933f210/app/imports/ui/components/AddMedication.jsx#L134-L199

**Comment by len-nguyen** [comment]
DispenseLog.jsx

Architecture: 
- All good

Design:
- DE-03: Remove unused code
- DE-05: Remove unwanted comments not relating to the file

Javascript:
- JS-03: use object deconstruction 

React:
- All good

UI:
- UI-02: Page is not responsive for mobile devices/smaller screens

------------------------------------------------------------------

AddMedication.jsx

Architecture: 
- All good

Design:
- All good

Javascript:
- JS-03: use object deconstruction 

React:
- All good

UI:
- UI-02: Page is not responsive for mobile devices/smaller screens

**Comment by mujtaba-a-quadri** [comment]
DispenseLog.jsx:

Architecture
AR-01: file name is not in camelCase

Design
DE-03: line 5: remove underscore import (commented out already)

Javascript/ESLint
JS-03: line 41: use object deconstruction

React
Fulfills all react requirements

UI
UI-02: Table gets cut off on mobile size screen, and navbar does not appear as expected.


AddMedication.jsx:

Architecture
AR-01: file name is not in camelCase

Design
Fulfills all design requirements

Javascript/ESLint
JS-03: line 82: use object deconstruction

React
Fulfills all react requirements

UI
UI-02: Container with form becomes too thin on mobile device, and navbar does not appear as expected

**Comment by JakeHiji** [comment]
DispenseLog.jsx
Architecture: good

JavaScript: good

Design: 
- no need for div (not named for css or anything)
- delete commented out unused underscore import/code

React: good

UI: good

AddMedication.jsx
Architecture: good

JavaScript: good

Design: 
- add some comments to code 
- delete commented out unused code, lines 67-74

React: good

UI: good
