### ISSUE TITLE
Review: Status.jsx and DispenseMedication.jsxReview: 

### ISSUE THREAD

**Issue by guanhongl** [minerva-medical/minerva-matrp#79]
## Review Branch

* [review-79](https://github.com/minerva-medical/minerva-matrp/issues/79)

## Files to be Reviewed

* [Status.jsx](https://github.com/minerva-medical/minerva-matrp/blob/main/app/imports/ui/pages/Status.jsx)  
* [DispenseMedication.jsx](https://github.com/minerva-medical/minerva-matrp/blob/main/app/imports/ui/components/DispenseMedication.jsx)

## Checklists

* [Architecture](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-architecture-checklist)
* [Design](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-design-checklist)
* [JS](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-js-checklist)
* [React](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-react-checklist)
* [UI](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-ui-checklist)

## Specific Requests for this request 

Reviewing the Status page as there should now be pagination, filtering, and sorting.
Reviewing the Dispense Medication page as there should now be filtering.

## Due Date 

12:00 pm Tuesday, November 2 2021
## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by alyssandra-cabading** [comment]
### Status.jsx
**Architecture**

> AR-01: Meets Requirement
> AR-02: Meets Requirement
> AR-03: Meets Requirement
------------------------------------------------------------------------------
**Design**
DE-01: Meets Requirement
DE-02: L75-L123 Nested if statement, maybe you can do an “||” operator to narrow it down to one “if statement” 
DE-03: Meets Requirement
DE-04: Meets Requirement
DE-05: Meets Requirement
DE-06: Meets Requirement
DE-07: Meets Requirement
DE-08: Meets Requirement

------------------------------------------------------------------------------
Javascript and ESLint Checklist
Javascript
JS-01: Meets Requirement
JS-02: Not Applicable
JS-03: Meets Requirement
JS-04: Meets Requirement
JS-05: Meets Requirement
JS-06: Meets Requirement
JS-07: Meets Requirement
ESLint
ES-01: Meets Requirement
ES-02: Meets Requirement
------------------------------------------------------------------------------
React Checklist
RE-01: Meets Requirement
RE-02: Not Applicable
RE-03: Meets Requirement
RE-04: Meets Requirement
RE-06: Meets Requirement
RE-07: Meets Requirement
RE-08: Meets Requirement
RE-09: Meets Requirement
RE-10: Meets Requirement
------------------------------------------------------------------------------
UI
UI-01: Meets Requirement
UI-02: Meets Requirement
UI-03: Meets Requirement
UI-04: Meets Requirement
UI-05: Meets Requirement
UI-06: Meets Requirement
UI-07: Meets Requirement

==============================================================================
DispenseMedication.jsx
Architecture
AR-01: Meets Requirement
AR-02: Meets Requirement
AR-03: Meets Requirement
------------------------------------------------------------------------------
Design
DE-01: Meets Requirement
DE-02: Meets Requirement
DE-03: Meets Requirement
DE-04: Meets Requirement
DE-05: Meets Requirement
DE-06: Meets Requirement
DE-07: Meets Requirement
DE-08: Meets Requirement
------------------------------------------------------------------------------
Javascript and ESLint Checklist
Javascript
JS-01: Meets Requirement
JS-02: Not Applicable
JS-03: Meets Requirement
JS-04: Meets Requirement
JS-05: Meets Requirement
JS-06: Meets Requirement
JS-07: Meets Requirement
ESLint
ES-01: Meets Requirement
ES-02: Meets Requirement
------------------------------------------------------------------------------
React Checklist
RE-01: Meets Requirement
RE-02: Meets Requirement
RE-03: Meets Requirement
RE-04: Meets Requirement
RE-06: Meets Requirement
RE-07: Meets Requirement
RE-08: Meets Requirement
RE-09: Meets Requirement
RE-10: Meets Requirement
------------------------------------------------------------------------------
UI
UI-01: Meets Requirement
UI-02: Meets Requirement
UI-03: Meets Requirement
UI-04: Meets Requirement
UI-05: Meets Requirement
UI-06: Meets Requirement
UI-07: Meets Requirement

**Comment by cammoore** [comment]
## Status.jsx

Should this be return false? 0 is falsey, but it isn't clear.
https://github.com/minerva-medical/minerva-matrp/blob/bca125e307e80f9a8414d58028e73346b63f494c/app/imports/ui/pages/Status.jsx#L82

Can you filter by more than one thing at a time? It doesn't look like
it.

## DispenseMedication.jsx

Why are we updating the name, brand, etc. Can't we just set quantity
to 0?
https://github.com/minerva-medical/minerva-matrp/blob/bca125e307e80f9a8414d58028e73346b63f494c/app/imports/ui/components/DispenseMedication.jsx#L38

Use consts in withTracker
https://github.com/minerva-medical/minerva-matrp/blob/bca125e307e80f9a8414d58028e73346b63f494c/app/imports/ui/components/DispenseMedication.jsx#L220

**Comment by guanhongl** [comment]
##Status.jsx
Architecture
	OK
Design
	DE-02: L73-149: use switch statements instead of nested if statements
	DE-09: L73-149: filtering should be handled in a function
JS
	OK
React
	L46-47: variables should be moved to state
UI
	Dropdown search query is squished

##DispenseMedication.jsx
Architecture
	OK
Design
	OK
JS
	OK
React
	RE-06: define L222-227 as const in withTracker()
UI
	OK

**Comment by mujtaba-a-quadri** [comment]
Status.jsx:

Architecture
AR-01: file name is not in camelCase

Design
Fulfills all design requirements

Javascript/ESLint
Fulfills all JS/ESLint requirements 

React
Fulfills all react requirements

UI
UI-02: Layout does not work as expected on mobile-sized screen (table doesn’t look right)
UI-03: the dropdowns do not make the mouse give the clicker icon (they give a cursor for typing instead)

DispenseMedication.jsx:

Architecture
AR-01: file name is not in camelCase

Design
Fulfills all design requirements

Javascript/ESLint
Fulfills all JS/ESLint requirements 

React
Fulfills all react requirements

UI
Fulfills all UI requirements

**Comment by glarita** [comment]
### Status.jsx

DE-02: 73-78 Is there a better way to filter this?

UI-01: The goal of the page is clear, but its kind of long. Maybe we can add comments briefly explaining some the functions on this page?

### DispenseMedication.jsx

UI-01: The goal of the page is clear, but its kind of long. Maybe we can add a few more comments briefly explaining some the functions. Other than that, comments are helpful in differentiating the purpose of each section of code

**Comment by jnocampo** [comment]
Status.jsx 

Architecture: 
AR-01 - AR-3: Meet Requirements

Design:
DE-01, DE-03 - DE-07:  All good, requirements met. 
DE-02: 
	- Lines 75 - 123: nested if statement can be rewritten

JavaScript & ESLint:
JS-01- JS-07: All good, requirements met. 
ES-01/02: All good, requirements met. 

React:
RE-01 - RE-10: All good, requirements met. 

UI:
UI-01, UI-03 - UI-07:  All good, requirements met. 
UI-02: Different screen sizes could still be adjusted


DispenseMedication.jsx

Architecture:
AR-01 - AR-03:  All good, requirements met. 

Design: 
DE-01 - DE-08:  All good, requirements met. 

JavaScript & ESLint:
JS-01- JS-07: All good, requirements met. 
ES-01/02: All good, requirements met. 

React:
RE-01 - RE-10: All good, requirements met. 

UI:
UI-01 - UI-07:  All good, requirements met.

**Comment by len-nguyen** [comment]
Architecture: 
- All good

Design:
- nested if statement

Javascript:
- All good

React:
- All good

UI:
- All good

------------------------------------------------------------------

DispenseMedication.jsx

Architecture: 
- All good

Design:
- All good

Javascript:
- All good

React:
- All good

UI:
- All good
